<div class="row">
	<div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"><i class="fa fa-mobile-phone"></i> Two-Factor Authentication</h3>
			</div>
			<div class="panel-body">
				<p>
					Enter the verification code generated by your mobile application.
				</p>
				<!-- IF error -->
				<div class="alert alert-danger">
				{error}
				</div>
				<!-- ENDIF error -->
				<form role="form" method="post">
					<div class="form-group">
						<input type="text" class="form-control input-lg text-center" id="code" name="code" />
					</div>
					<input type="hidden" id="csrf" name="csrf" value="{config.csrf_token}" />
					<button class="btn btn-block btn-primary text-center" type="submit">Verify</button>
				</form>
			</div>
		</div>
	</div>
</div>